title: "Distribution Normalization: An “Effortless” Test-Time Augmentation for Contrastively Learned Visual-language Models"
description: "A NeurIPS 2023 Paper by"
buttons:
  arXiv: 'https://arxiv.org/abs/2210.08607'
  Code: "https://github.com/fengyuli-dev/distribution-normalization"
  Poster: 'https://arxiv.org/abs/2210.08607'
  Video: 'https://arxiv.org/abs/2210.08607'
  Slides: 'https://arxiv.org/abs/2210.08607'
theme: jekyll-theme-cayman